# Generated by Django 4.2.6 on 2024-06-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passwod',
            new_name='password',
        ),
    ]
