# Generated by Django 4.2.6 on 2024-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_passwod_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='client', max_length=50, verbose_name='name'),
        ),
    ]
