# Generated by Django 4.2.6 on 2024-06-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_shipment_about_shipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='reserved_date',
            new_name='received_date',
        ),
    ]
