# Generated by Django 4.2.6 on 2024-06-24 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_shipment_id_alter_shipment_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')]),
        ),
    ]
